# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenMarketUIkit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenMarketUIkit

  target 'OpenMarketUIkitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenMarketUIkitUITests' do
    # Pods for testing
  end
  

end
