# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

def pods
  # Pods for OpenMarket
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxRelay'
  pod 'SnapKit', '~> 5.6.0'
  pod 'Kingfisher', '~> 7.0'
end

target 'OpenMarket' do
  pods
end

target 'ProductRegistTest' do
  pods
end

target 'ProductEditTest' do
  pods
end
